### ISSUE TITLE
553 error from pure-ftpd container

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/sdx-compose#27]
On my ubuntu 17.04 box I am getting an error from sdx-downstream stating: `error_perm("553 Can't open that file: No such file or directory",)`. This is causing a nacking circle between multiple services and overwhelming the logging output.

**Comment by JamesGardiner** [comment]
Looks like this was introduced in edb4be72c528bf6863ac751

**Comment by collisdigital** [comment]
@JamesGardiner is this still an issue?

**Comment by insacuri** [comment]
Not seen this in a long while.  Going to close it and we can reopen if it becomes an issue again
