### ISSUE TITLE
Prefer shell script to python virtualenv

### ISSUE THREAD

**Issue by necrophonic** [ONSdigital/sdx-compose#37]
Currently uses a python virtualenv to generate symmetric keys for testing. Should be able to remove that dependency and use a simple shell script.

Alternative would be to spin up something in another docker container that can write the keys back to a shared volume.

**Comment by necrophonic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create bash script for generating symmetric keys in sdx-compose](https://trello.com/c/oy42VWy8/478-create-bash-script-for-generating-symmetric-keys-in-sdx-compose)

**Comment by insacuri** [comment]
Using hard coded keys in dev now so this can be closed.
